import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartHydration from "@/components/storefront/cart/cart-hydration";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
    title: "DEMO SHOP",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>

            <body suppressHydrationWarning className="bg-stone-50 min-h-full flex flex-col">

                <CartHydration />

                {children}

            </body>

        </html>
    );
}