import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import CartHydration from "@/components/storefront/cart/cart-hydration";
import SiteHeader from "@/components/layout/header/site-header";
import FooterSection from "@/components/layout/footer/footer-section";

const plusJakartaSans = Plus_Jakarta_Sans({ variable: "--font-sans", subsets: ["latin"] });

export const metadata = {
    title: "DEMO SHOP",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${plusJakartaSans.variable} min-h-full antialiased`}>

            <body suppressHydrationWarning className="h-full flex">

                <div className="flex flex-col flex-1 bg-white">

                    <CartHydration />

                    <SiteHeader />

                    {children}

                    <FooterSection />

                </div>

            </body>

        </html>
    );
}