import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import CartHydration from "@/components/storefront/cart/cart-hydration";
import SiteHeader from "@/components/layout/header/site-header";
import FooterSection from "@/components/layout/footer/footer-section";

const plusJakartaSans = Plus_Jakarta_Sans({ variable: "--font-sans", subsets: ["latin"] });
const geistMono = Plus_Jakarta_Sans({ variable: "--font-mono", subsets: ["latin"] });

export const metadata = {
    title: "DEMO SHOP",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${plusJakartaSans.variable} ${geistMono.variable} h-full antialiased`}>

            <body suppressHydrationWarning className="bg-stone-50 min-h-full flex flex-col">

                <CartHydration />

                <SiteHeader />
                
                {children}

                <FooterSection />

            </body>

        </html>
    );
}